// resources/js/Pages/Auth/Login.vue
<template>
  <div class="min-h-screen bg-[#f0f2f5] flex items-center justify-center p-4 font-sans">
    <div class="bg-white p-10 rounded-lg shadow-[0_4px_12px_rgba(0,0,0,0.1)] w-full max-w-[400px]">
      
      <div class="text-center mb-8">
        <h1 class="text-[#3498db] text-2xl font-semibold m-0">Rate My Staff</h1>
        <p class="text-[#5f6368] text-sm mt-2">Admin Dashboard Panel</p>
      </div>

      <div v-if="error" class="bg-[#fce8e6] text-[#d93025] p-3 rounded text-[13px] mb-5 border-l-4 border-[#d93025]">
        {{ error }}
      </div>

      <form @submit.prevent="login">
        <div class="mb-5 relative">
          <label for="email" class="block text-[14px] text-[#3c4043] mb-2 font-medium">Username or Email</label>
          <input 
            type="text" 
            id="email" 
            v-model="form.email"
            placeholder="admin@example.com"
            class="w-full p-3 border border-[#dadce0] rounded text-[16px] transition-colors focus:outline-none focus:border-[#3498db] focus:ring-1 focus:ring-[#3498db]"
            required
          >
        </div>

        <div class="mb-5 relative">
          <label for="password" class="block text-[14px] text-[#3c4043] mb-2 font-medium">Password</label>
          <input 
            type="password" 
            id="password" 
            v-model="form.password"
            placeholder="••••••••"
            class="w-full p-3 border border-[#dadce0] rounded text-[16px] transition-colors focus:outline-none focus:border-[#3498db] focus:ring-1 focus:ring-[#3498db]"
            required
          >
        </div>

        <div class="text-right mt-2 mb-4">
          <a href="#" class="text-[13px] text-[#3498db] hover:underline">Forgot password?</a>
        </div>

        <button 
          type="submit" 
          :disabled="isLoading"
          class="w-full p-3 bg-[#3498db] text-white border-0 rounded text-[16px] font-medium cursor-pointer transition-colors hover:bg-[#2980b9] disabled:bg-opacity-70 disabled:cursor-not-allowed"
        >
          <span v-if="isLoading">Signing in...</span>
          <span v-else>Sign In</span>
        </button>
      </form>

      <div class="mt-8 text-center text-[12px] text-[#70757a]">
        <p>Don't have an account? <a href="#" class="text-[#3498db] hover:underline">Contact System Administrator</a></p>
        <p class="mt-2">&copy; {{ new Date().getFullYear() }} Rate My Staff Dashboard</p>
      </div>

    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue';
import axios from 'axios';

const form = reactive({
  email: '',
  password: ''
});

const error = ref('');
const isLoading = ref(false);

const login = async () => {
  error.value = '';
  isLoading.value = true;
  
  try {
    await axios.get('/sanctum/csrf-cookie');
    const response = await axios.post('/login', form);
    
    // Attempt redirect on success
    window.location.href = '/dashboard';
    
  } catch (err) {
    if (err.response && err.response.data && err.response.data.message) {
      error.value = err.response.data.message;
    } else {
      error.value = 'Invalid username or password. Please try again.';
    }
  } finally {
    isLoading.value = false;
  }
};
</script>

// web-next/app/(auth)/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { signIn } from "next-auth/react";

export default function LoginPage() {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    setLoading(true);
    const res = await signIn("credentials", { email, password, redirect: false });
    setLoading(false);
    if (res?.error) {
      setError("Email atau password salah.");
      return;
    }
    router.push("/dashboard");
    router.refresh();
  }

  return (
    <main className="flex min-h-screen items-center justify-center bg-slate-100 p-4">
      <form
        onSubmit={handleSubmit}
        className="w-full max-w-sm space-y-4 rounded-2xl bg-white p-8 shadow-lg"
      >
        <div className="text-center">
          <h1 className="text-2xl font-bold text-slate-800">RateMyStaff</h1>
          <p className="mt-1 text-sm text-slate-500">Masuk ke dashboard admin</p>
        </div>

        {error && (
          <div className="rounded-lg bg-red-50 px-3 py-2 text-sm text-red-600">{error}</div>
        )}

        <div className="space-y-1">
          <label className="text-sm font-medium text-slate-700">Email</label>
          <input
            type="email"
            required
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-500"
            placeholder="admin@ratemystaff.local"
          />
        </div>

        <div className="space-y-1">
          <label className="text-sm font-medium text-slate-700">Password</label>
          <input
            type="password"
            required
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none focus:border-slate-500"
            placeholder="••••••••"
          />
        </div>

        <button
          type="submit"
          disabled={loading}
          className="w-full rounded-lg bg-slate-800 py-2 text-sm font-semibold text-white transition hover:bg-slate-700 disabled:opacity-60"
        >
          {loading ? "Memproses…" : "Masuk"}
        </button>
      </form>
    </main>
  );
}
