// web-next/app/(public)/link-expired/page.tsx
export default function LinkExpiredPage() {
  return (
    <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-indigo-100 via-slate-100 to-purple-100 p-4">
      <div className="text-center">
        <div className="mx-auto mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-amber-100 text-2xl">
          ⏰
        </div>
        <h2 className="text-xl font-bold text-slate-800">Tautan Kadaluarsa</h2>
        <p className="mt-1 text-slate-500">Tautan ini sudah tidak berlaku. Hubungi HR untuk tautan baru.</p>
      </div>
    </main>
  );
}

// resources/js/Pages/Public/LinkExpired.vue
<template>
  <div class="min-h-screen bg-gray-50 flex flex-col justify-center items-center p-4">
    <div class="w-full max-w-md bg-white p-8 rounded-3xl shadow-xl border border-gray-100 text-center">
      <div class="w-16 h-16 bg-red-50 text-red-500 rounded-full flex items-center justify-center mx-auto mb-4 text-3xl">
        ⏱️
      </div>
      <h1 class="text-2xl font-bold text-gray-800 mb-2">Tautan Kadaluwarsa</h1>
      <p class="text-gray-500 mb-6">Maaf, tautan formulir perizinan ini sudah tidak berlaku, atau Anda menggunakan tautan yang salah.</p>
      
      <p class="text-sm text-gray-400">Silakan hubungi HR/Admin Anda untuk meminta tautan yang baru.</p>
    </div>
  </div>
</template>

<script setup>
</script>
