// resources/js/Pages/Public/LinkExpired.vue
<template>
  <div class="min-h-screen bg-gray-50 flex flex-col justify-center items-center p-4">
    <div class="w-full max-w-md bg-white p-8 rounded-3xl shadow-xl border border-gray-100 text-center">
      <div class="w-16 h-16 bg-red-50 text-red-500 rounded-full flex items-center justify-center mx-auto mb-4 text-3xl">
        ⏱️
      </div>
      <h1 class="text-2xl font-bold text-gray-800 mb-2">Tautan Kadaluwarsa</h1>
      <p class="text-gray-500 mb-6">Maaf, tautan formulir perizinan ini sudah tidak berlaku, atau Anda menggunakan tautan yang salah.</p>
      
      <p class="text-sm text-gray-400">Silakan hubungi HR/Admin Anda untuk meminta tautan yang baru.</p>
    </div>
  </div>
</template>

<script setup>
</script>

// app/(public)/link-expired/page.tsx
import { IconAlert } from "@/components/ui/icons";

export default function LinkExpiredPage() {
  return (
    <main className="ambient relative flex min-h-screen items-center justify-center bg-bg p-4">
      <div className="glass-2 relative z-10 w-full max-w-md rounded-3xl p-6 text-center shadow-2xl sm:p-8">
        <span
          className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl text-warning"
          style={{ background: "color-mix(in oklab, var(--warning) 16%, transparent)" }}
        >
          <IconAlert className="text-[26px]" />
        </span>
        <h2 className="font-display text-xl font-bold text-fg">Tautan Kadaluarsa</h2>
        <p className="mt-1 text-muted">Tautan ini sudah tidak berlaku. Hubungi HR untuk tautan baru.</p>
      </div>
    </main>
  );
}
